name: Auto Bump Version and Tag

on:
  push:
    branches:
      - main

jobs:
  bump_and_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important to fetch all tags

      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Optional: defaults can be configured to set DEFAULT_BUMP, WITH_V, etc.
          DEFAULT_BUMP: patch

      - name: Build and Publish Package
        run: |
          python -m pip install --upgrade pip build
          python -m build
          # Add your package publish step here (e.g., using pypa/gh-action-pypi-publish)
